/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2021-05-13 09:07:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import MemberManagement.dto.MemberManagementVO;

public final class memberInfoUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	MemberManagementVO mv = (MemberManagementVO)request.getAttribute("mv");
	

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>회원 등록하기</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <style>\r\n");
      out.write("    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */\r\n");
      out.write("    .row.content {height: 683px}\r\n");
      out.write("    \r\n");
      out.write("    /* Set gray background color and 100% height */\r\n");
      out.write("    .sidenav {\r\n");
      out.write("      background-color: #f1f1f1;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* Set black background color, white text and some padding */\r\n");
      out.write("    footer {\r\n");
      out.write("      background-color: #555;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* On small screens, set height to 'auto' for sidenav and grid */\r\n");
      out.write("    @media screen and (max-width: 767px) {\r\n");
      out.write("      .sidenav {\r\n");
      out.write("        height: auto;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .row.content {height: auto;} \r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("  <div class=\"row content\">\r\n");
      out.write("    <div class=\"col-sm-3 sidenav\">\r\n");
      out.write("      <h4>MEMBER MANAGEMENT</h4>\r\n");
      out.write("      <ul class=\"nav nav-pills nav-stacked\">\r\n");
      out.write("        <li><a href=\"##\">Home</a></li>\r\n");
      out.write("        <li><a href=\"/servlet_default/MemberInfoServlet\">회원정보등록</a></li>\r\n");
      out.write("        <li><a href=\"/servlet_default/MemberManagementServlet\">회원정보조회</a></li>\r\n");
      out.write("      </ul><br>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" placeholder=\"Search Blog..\">\r\n");
      out.write("        <span class=\"input-group-btn\">\r\n");
      out.write("          <button class=\"btn btn-default\" type=\"button\">\r\n");
      out.write("            <span class=\"glyphicon glyphicon-search\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-sm-9\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t  <h2>Changing information</h2>\r\n");
      out.write("\t\t<form id=\"fm\">\r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t      <label for=\"memId\">I\tD:</label>\r\n");
      out.write("\t      <input type=\"text\" class=\"form-control\" id=\"memId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mv.memId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"memId\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t      <label for=\"memPass\">비밀번호:</label>\r\n");
      out.write("\t      <input type=\"text\" class=\"form-control\" id=\"memPass\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mv.memPass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"memPass\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t      <label for=\"memHp\">전화번호:</label>\r\n");
      out.write("\t      <input type=\"text\" class=\"form-control\" id=\"memHp\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mv.memHp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"memHp\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t      <label for=\"memEmail\">이메일:</label>\r\n");
      out.write("\t      <input type=\"text\" class=\"form-control\" id=\"memEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mv.memEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"memEmail\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<button type=\"button\" id=\"updateBtn\" class=\"btn btn-primary\" onclick=\"update()\">정보수정</button>\r\n");
      out.write("\t    <button id=\"deleteBtn\" type=\"button\" class=\"btn btn-primary\">삭제</button>\r\n");
      out.write("\t  </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container-fluid\">\r\n");
      out.write("  <p>2021-05-11 대덕인재개발원 403 김민지</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function update() {\r\n");
      out.write("\tif(confirm(\"수정 하시겠습니까?\")){\r\n");
      out.write("\t\talert(\"수정되었습니다.\");\r\n");
      out.write("\t\tvar fm = document.getElementById(\"fm\");\r\n");
      out.write("\t\tfm.method = \"post\";\r\n");
      out.write("\t\tfm.action = \"/servlet_default/MemberInfoUpdateServlet\"\r\n");
      out.write("\t\tfm.submit();\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#deleteBtn\").click(function(){\r\n");
      out.write("\tif(confirm(\"정말로 삭제하시겠습니까?\")){\r\n");
      out.write("\t\talert(\"삭제되었습니다.\");\r\n");
      out.write("\t\tvar fm = document.getElementById(\"fm\");\r\n");
      out.write("\t\tfm.method = \"post\";\r\n");
      out.write("\t\tfm.action = \"/servlet_default/MemberInfoDeleteServlet\";\r\n");
      out.write("\t\tfm.submit();\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
